import { calculateEmi } from './emi.js';
import { sanitize, validateApplication } from './validation.js';

const $ = (selector, scope = document) => scope.querySelector(selector);
const $$ = (selector, scope = document) => [...scope.querySelectorAll(selector)];
const formatCurrency = value => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value);

function initNavigation() { const button = $('.menu-button'); const menu = $('.nav-menu'); button.addEventListener('click', () => { const open = menu.classList.toggle('is-open'); button.setAttribute('aria-expanded', String(open)); button.textContent = open ? '×' : '☰'; }); $$('.nav-menu a').forEach(link => link.addEventListener('click', () => { menu.classList.remove('is-open'); button.setAttribute('aria-expanded', 'false'); button.textContent = '☰'; })); }
function initCalculator() { const amount = $('#loan-amount'), rate = $('#interest-rate'), term = $('#loan-term'); const render = () => { const result = calculateEmi(Number(amount.value), Number(rate.value), Number(term.value)); $('#amount-output').value = formatCurrency(amount.value); $('#rate-output').value = `${rate.value}% p.a.`; $('#term-output').value = `${term.value} ${term.value === '1' ? 'year' : 'years'}`; $('#emi-output').textContent = formatCurrency(result.emi); $('#interest-output').textContent = `Total interest: ${formatCurrency(result.interest)}`; }; [amount, rate, term].forEach(input => input.addEventListener('input', render)); render(); }
function initApplication() { const modal = $('#apply-modal'), form = $('#application-form'), error = $('#form-error'); const open = service => { form.reset(); error.textContent = ''; $('#success-message').hidden = true; form.hidden = false; if (service) form.elements.service.value = service; modal.showModal(); form.elements.name.focus(); }; const close = () => modal.close(); $$('[data-open-apply]').forEach(button => button.addEventListener('click', () => open(button.dataset.service))); $$('[data-close-modal]').forEach(button => button.addEventListener('click', close)); form.addEventListener('submit', async event => { event.preventDefault(); const data = Object.fromEntries(new FormData(form)); data.name = sanitize(data.name); data.mobile = String(data.mobile).replace(/\D/g, ''); data.message = sanitize(data.message); data.consent = form.elements.consent.checked; const message = validateApplication(data); if (message || !data.consent) { error.textContent = message || 'Please provide consent to submit your enquiry.'; return; } const button = form.querySelector('[type="submit"]'); button.disabled = true; button.textContent = 'Submitting…'; try { const response = await fetch('/api/enquiries', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Submission failed.'); form.hidden = true; $('#reference-id').textContent = result.reference_id; $('#success-message').hidden = false; } catch (requestError) { error.textContent = requestError.message || 'Unable to submit right now. Please call us.'; } finally { button.disabled = false; button.textContent = 'Submit enquiry'; } }); }
let toastTimer; function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('visible'); clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.remove('visible'), 5200); }
document.addEventListener('DOMContentLoaded', () => { $('[data-current-year]').textContent = new Date().getFullYear(); initNavigation(); initCalculator(); initApplication(); });
